// Auto-generated from Tech_Headcount_Monthly_Apr25_Mar26.xlsx
// Fiscal year: Apr-Mar
const HARDCODED_MONTHLY_HEADCOUNT = {
  '2025-04': {
    'Houston Cal Lab': 28,
    'Biomedical': 31,
    'Philadelphia Cal Lab': 30,
    'Rochester Cal Lab': 28,
    'Montreal Cal Lab': 25,
    'Pipettes Milford Lab': 24,
    'Dayton Cal Lab': 20,
    'Toronto Cal Lab': 20,
    'Charlotte Cal Lab': 15,
    'Denver Cal Lab': 12,
    'Pittsburgh Cal Lab': 12,
    'Los Angeles Cal Lab': 16,
    'Chesapeake Cal Lab': 8,
    'Cleveland Cal Lab': 10,
    'St. Louis Cal Lab': 10,
    'Pipettes Field Service': 12,
    'Boston Cal Lab': 10,
    'Portland Cal Lab': 6,
    'Phoenix Cal Lab': 8,
    'San Diego Cal Lab': 6,
    'Tangent Indianapolis Lab': 4,
    'Palm Beach Cal Lab': 2,
    'Ottawa Cal Lab': 3,
    'Tangent Decatur Cal Lab': 3,
    'Pipettes San Diego Lab': 3,
    'Puerto Rico Cal Lab': 2,
  },
  '2025-05': {
    'Houston Cal Lab': 28,
    'Biomedical': 30,
    'Philadelphia Cal Lab': 30,
    'Rochester Cal Lab': 27,
    'Montreal Cal Lab': 25,
    'Pipettes Milford Lab': 24,
    'Dayton Cal Lab': 20,
    'Toronto Cal Lab': 20,
    'Charlotte Cal Lab': 15,
    'Denver Cal Lab': 14,
    'Pittsburgh Cal Lab': 13,
    'Los Angeles Cal Lab': 14,
    'Chesapeake Cal Lab': 9,
    'Cleveland Cal Lab': 10,
    'St. Louis Cal Lab': 10,
    'Pipettes Field Service': 12,
    'Boston Cal Lab': 10,
    'Portland Cal Lab': 6,
    'Phoenix Cal Lab': 7,
    'San Diego Cal Lab': 6,
    'Tangent Indianapolis Lab': 3,
    'Palm Beach Cal Lab': 2,
    'Ottawa Cal Lab': 3,
    'Tangent Decatur Cal Lab': 3,
    'Pipettes San Diego Lab': 3,
    'Puerto Rico Cal Lab': 2,
  },
  '2025-06': {
    'Houston Cal Lab': 28,
    'Biomedical': 28,
    'Philadelphia Cal Lab': 30,
    'Rochester Cal Lab': 28,
    'Montreal Cal Lab': 26,
    'Pipettes Milford Lab': 23,
    'Dayton Cal Lab': 19,
    'Toronto Cal Lab': 19,
    'Charlotte Cal Lab': 15,
    'Denver Cal Lab': 14,
    'Pittsburgh Cal Lab': 12,
    'Los Angeles Cal Lab': 13,
    'Chesapeake Cal Lab': 9,
    'Cleveland Cal Lab': 10,
    'St. Louis Cal Lab': 9,
    'Pipettes Field Service': 12,
    'Boston Cal Lab': 9,
    'Portland Cal Lab': 7,
    'Phoenix Cal Lab': 7,
    'San Diego Cal Lab': 6,
    'Tangent Indianapolis Lab': 4,
    'Palm Beach Cal Lab': 2,
    'Ottawa Cal Lab': 3,
    'Tangent Decatur Cal Lab': 3,
    'Pipettes San Diego Lab': 3,
    'Puerto Rico Cal Lab': 2,
  },
  '2025-07': {
    'Houston Cal Lab': 29,
    'Biomedical': 29,
    'Philadelphia Cal Lab': 31,
    'Rochester Cal Lab': 30,
    'Montreal Cal Lab': 26,
    'Pipettes Milford Lab': 21,
    'Dayton Cal Lab': 18,
    'Toronto Cal Lab': 20,
    'Charlotte Cal Lab': 14,
    'Denver Cal Lab': 13,
    'Pittsburgh Cal Lab': 12,
    'Los Angeles Cal Lab': 14,
    'Chesapeake Cal Lab': 9,
    'Cleveland Cal Lab': 11,
    'St. Louis Cal Lab': 9,
    'Pipettes Field Service': 12,
    'Boston Cal Lab': 9,
    'Portland Cal Lab': 7,
    'Phoenix Cal Lab': 7,
    'San Diego Cal Lab': 6,
    'Tangent Indianapolis Lab': 5,
    'Palm Beach Cal Lab': 2,
    'Honda E Liberty, OH (ELP)': 2,
    'Honda Greensburg IN (IAP)': 3,
    'Ottawa Cal Lab': 3,
    'Tangent Decatur Cal Lab': 3,
    'Pipettes San Diego Lab': 3,
    'Honda Dayton, OH': 1,
    'Puerto Rico Cal Lab': 2,
    'Honda Anna, OH (AEP)': 1,
    'Honda Marysville OH (MAP)': 4,
  },
  '2025-08': {
    'Houston Cal Lab': 28,
    'Biomedical': 30,
    'Philadelphia Cal Lab': 31,
    'Rochester Cal Lab': 29,
    'Montreal Cal Lab': 26,
    'Pipettes Milford Lab': 21,
    'Dayton Cal Lab': 18,
    'Toronto Cal Lab': 20,
    'Charlotte Cal Lab': 14,
    'Denver Cal Lab': 13,
    'Pittsburgh Cal Lab': 12,
    'Los Angeles Cal Lab': 14,
    'Chesapeake Cal Lab': 9,
    'Cleveland Cal Lab': 12,
    'St. Louis Cal Lab': 10,
    'Pipettes Field Service': 12,
    'Boston Cal Lab': 9,
    'Portland Cal Lab': 7,
    'Honda Lincoln, AL (AAP)': 6,
    'Phoenix Cal Lab': 7,
    'San Diego Cal Lab': 6,
    'Tangent Indianapolis Lab': 6,
    'Palm Beach Cal Lab': 2,
    'Honda E Liberty, OH (ELP)': 3,
    'Honda Greensburg IN (IAP)': 3,
    'Ottawa Cal Lab': 3,
    'Tangent Decatur Cal Lab': 3,
    'Pipettes San Diego Lab': 2,
    'Honda Dayton, OH': 2,
    'Puerto Rico Cal Lab': 2,
    'Honda Anna, OH (AEP)': 1,
    'Honda Marysville OH (MAP)': 4,
  },
  '2025-09': {
    'Houston Cal Lab': 28,
    'Biomedical': 30,
    'Philadelphia Cal Lab': 31,
    'Rochester Cal Lab': 29,
    'Montreal Cal Lab': 26,
    'Pipettes Milford Lab': 21,
    'Dayton Cal Lab': 18,
    'Toronto Cal Lab': 20,
    'Charlotte Cal Lab': 14,
    'Denver Cal Lab': 13,
    'Pittsburgh Cal Lab': 12,
    'Los Angeles Cal Lab': 15,
    'Chesapeake Cal Lab': 8,
    'Cleveland Cal Lab': 12,
    'St. Louis Cal Lab': 11,
    'Pipettes Field Service': 11,
    'Boston Cal Lab': 9,
    'Portland Cal Lab': 7,
    'Honda Lincoln, AL (AAP)': 6,
    'Phoenix Cal Lab': 7,
    'San Diego Cal Lab': 6,
    'Tangent Indianapolis Lab': 6,
    'Palm Beach Cal Lab': 2,
    'Honda E Liberty, OH (ELP)': 3,
    'Honda Greensburg IN (IAP)': 3,
    'Ottawa Cal Lab': 3,
    'Tangent Decatur Cal Lab': 3,
    'Pipettes San Diego Lab': 2,
    'Honda Dayton, OH': 2,
    'Puerto Rico Cal Lab': 2,
    'Honda Anna, OH (AEP)': 1,
    'Honda Marysville OH (MAP)': 2,
  },
  '2025-10': {
    'Houston Cal Lab': 29,
    'Biomedical': 31,
    'Philadelphia Cal Lab': 31,
    'Rochester Cal Lab': 29,
    'Montreal Cal Lab': 25,
    'Pipettes Milford Lab': 21,
    'Dayton Cal Lab': 18,
    'Toronto Cal Lab': 19,
    'Charlotte Cal Lab': 14,
    'Denver Cal Lab': 13,
    'Pittsburgh Cal Lab': 11,
    'Los Angeles Cal Lab': 15,
    'Chesapeake Cal Lab': 8,
    'Cleveland Cal Lab': 11,
    'St. Louis Cal Lab': 12,
    'Pipettes Field Service': 11,
    'Boston Cal Lab': 9,
    'Portland Cal Lab': 7,
    'Honda Lincoln, AL (AAP)': 7,
    'Phoenix Cal Lab': 7,
    'San Diego Cal Lab': 5,
    'Tangent Indianapolis Lab': 6,
    'Palm Beach Cal Lab': 2,
    'Honda E Liberty, OH (ELP)': 3,
    'Honda Greensburg IN (IAP)': 3,
    'Ottawa Cal Lab': 3,
    'Tangent Decatur Cal Lab': 3,
    'Pipettes San Diego Lab': 3,
    'Honda Dayton, OH': 2,
    'Puerto Rico Cal Lab': 2,
    'Honda Anna, OH (AEP)': 1,
    'Honda Marysville OH (MAP)': 2,
  },
  '2025-11': {
    'Houston Cal Lab': 30,
    'Biomedical': 31,
    'Philadelphia Cal Lab': 32,
    'Rochester Cal Lab': 28,
    'Montreal Cal Lab': 25,
    'Pipettes Milford Lab': 21,
    'Dayton Cal Lab': 18,
    'Toronto Cal Lab': 19,
    'Charlotte Cal Lab': 14,
    'Denver Cal Lab': 13,
    'Pittsburgh Cal Lab': 12,
    'Los Angeles Cal Lab': 15,
    'Chesapeake Cal Lab': 8,
    'Cleveland Cal Lab': 11,
    'St. Louis Cal Lab': 12,
    'Pipettes Field Service': 11,
    'Boston Cal Lab': 9,
    'Portland Cal Lab': 7,
    'Honda Lincoln, AL (AAP)': 8,
    'Phoenix Cal Lab': 7,
    'San Diego Cal Lab': 5,
    'Tangent Indianapolis Lab': 6,
    'Palm Beach Cal Lab': 2,
    'Honda E Liberty, OH (ELP)': 3,
    'Honda Greensburg IN (IAP)': 3,
    'Ottawa Cal Lab': 3,
    'Tangent Decatur Cal Lab': 3,
    'Pipettes San Diego Lab': 3,
    'Honda Dayton, OH': 2,
    'Puerto Rico Cal Lab': 2,
    'Honda Anna, OH (AEP)': 1,
    'Honda Marysville OH (MAP)': 3,
  },
  '2025-12': {
    'Houston Cal Lab': 30,
    'Biomedical': 31,
    'Philadelphia Cal Lab': 31,
    'Rochester Cal Lab': 28,
    'Montreal Cal Lab': 25,
    'Pipettes Milford Lab': 21,
    'Dayton Cal Lab': 18,
    'Toronto Cal Lab': 20,
    'Charlotte Cal Lab': 15,
    'Denver Cal Lab': 13,
    'Pittsburgh Cal Lab': 12,
    'Los Angeles Cal Lab': 15,
    'Chesapeake Cal Lab': 9,
    'Cleveland Cal Lab': 11,
    'St. Louis Cal Lab': 12,
    'Pipettes Field Service': 11,
    'Boston Cal Lab': 9,
    'Portland Cal Lab': 7,
    'Honda Lincoln, AL (AAP)': 8,
    'Phoenix Cal Lab': 7,
    'San Diego Cal Lab': 5,
    'Tangent Indianapolis Lab': 6,
    'Palm Beach Cal Lab': 2,
    'Honda E Liberty, OH (ELP)': 3,
    'Honda Greensburg IN (IAP)': 3,
    'Ottawa Cal Lab': 3,
    'Tangent Decatur Cal Lab': 3,
    'Pipettes San Diego Lab': 2,
    'Honda Dayton, OH': 2,
    'Puerto Rico Cal Lab': 2,
    'Honda Anna, OH (AEP)': 1,
    'Honda Marysville OH (MAP)': 3,
  },
  '2026-01': {
    'Houston Cal Lab': 31,
    'Biomedical': 31,
    'Philadelphia Cal Lab': 31,
    'Rochester Cal Lab': 29,
    'Montreal Cal Lab': 25,
    'Pipettes Milford Lab': 21,
    'Dayton Cal Lab': 18,
    'Toronto Cal Lab': 20,
    'Charlotte Cal Lab': 17,
    'Denver Cal Lab': 14,
    'Pittsburgh Cal Lab': 13,
    'Los Angeles Cal Lab': 13,
    'Chesapeake Cal Lab': 10,
    'Cleveland Cal Lab': 11,
    'St. Louis Cal Lab': 10,
    'Pipettes Field Service': 10,
    'Boston Cal Lab': 8,
    'Portland Cal Lab': 7,
    'Honda Lincoln, AL (AAP)': 8,
    'Phoenix Cal Lab': 6,
    'San Diego Cal Lab': 5,
    'Tangent Indianapolis Lab': 6,
    'Palm Beach Cal Lab': 3,
    'Honda E Liberty, OH (ELP)': 3,
    'Honda Greensburg IN (IAP)': 3,
    'Ottawa Cal Lab': 3,
    'Tangent Decatur Cal Lab': 3,
    'Pipettes San Diego Lab': 2,
    'Honda Dayton, OH': 2,
    'Puerto Rico Cal Lab': 2,
    'Honda Anna, OH (AEP)': 1,
    'Honda Marysville OH (MAP)': 3,
  },
  '2026-02': {
    'Houston Cal Lab': 30,
    'Biomedical': 31,
    'Philadelphia Cal Lab': 33,
    'Rochester Cal Lab': 27,
    'Montreal Cal Lab': 25,
    'Pipettes Milford Lab': 21,
    'Dayton Cal Lab': 18,
    'Toronto Cal Lab': 19,
    'Charlotte Cal Lab': 17,
    'Denver Cal Lab': 15,
    'Pittsburgh Cal Lab': 14,
    'Los Angeles Cal Lab': 13,
    'Chesapeake Cal Lab': 10,
    'Cleveland Cal Lab': 10,
    'St. Louis Cal Lab': 10,
    'Pipettes Field Service': 11,
    'Boston Cal Lab': 7,
    'Portland Cal Lab': 7,
    'Honda Lincoln, AL (AAP)': 8,
    'Phoenix Cal Lab': 7,
    'San Diego Cal Lab': 6,
    'Tangent Indianapolis Lab': 6,
    'Palm Beach Cal Lab': 3,
    'Honda E Liberty, OH (ELP)': 3,
    'Honda Greensburg IN (IAP)': 3,
    'Ottawa Cal Lab': 3,
    'Tangent Decatur Cal Lab': 3,
    'Pipettes San Diego Lab': 3,
    'Honda Dayton, OH': 2,
    'Puerto Rico Cal Lab': 2,
    'Honda Anna, OH (AEP)': 1,
    'Honda Marysville OH (MAP)': 3,
  },
  '2026-03': {
    'Houston Cal Lab': 31,
    'Biomedical': 31,
    'Philadelphia Cal Lab': 32,
    'Rochester Cal Lab': 28,
    'Montreal Cal Lab': 25,
    'Pipettes Milford Lab': 21,
    'Dayton Cal Lab': 19,
    'Toronto Cal Lab': 19,
    'Charlotte Cal Lab': 17,
    'Denver Cal Lab': 14,
    'Pittsburgh Cal Lab': 13,
    'Los Angeles Cal Lab': 13,
    'Chesapeake Cal Lab': 11,
    'Cleveland Cal Lab': 10,
    'St. Louis Cal Lab': 12,
    'Pipettes Field Service': 11,
    'Boston Cal Lab': 7,
    'Portland Cal Lab': 7,
    'Honda Lincoln, AL (AAP)': 7,
    'Phoenix Cal Lab': 7,
    'San Diego Cal Lab': 6,
    'Tangent Indianapolis Lab': 4,
    'Palm Beach Cal Lab': 5,
    'Honda E Liberty, OH (ELP)': 3,
    'Honda Greensburg IN (IAP)': 3,
    'Ottawa Cal Lab': 3,
    'Tangent Decatur Cal Lab': 3,
    'Pipettes San Diego Lab': 3,
    'Honda Dayton, OH': 2,
    'Puerto Rico Cal Lab': 2,
    'Honda Anna, OH (AEP)': 1,
    'Honda Marysville OH (MAP)': 2,
  },
};
